# .github/workflows/npm-publish-github-packages.yml
# This workflow will run tests using Node.js and then publish a package to GitHub Packages.
# It generates a new version starting from v1.0.0 and increments patch versions on each push.

name: Node.js Package

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches: 
      - main
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci

  version:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Increment version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          initial_version: '1.0.0'  # Inicia desde v1.0.0 si no hay tags previos
          tag_prefix: 'v'
          commit_message: 'ci: Increment version to {{version}}'

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: 'Release of version ${{ steps.tag_version.outputs.new_tag }}'
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-gpr:
    needs: [build, version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Set Git Identity
        run: |
          git config user.name "jjsierra"
          git config user.email "juanjosesierram@gmail.com"

      - name: Set GitHub Packages Auth
        run: |
          echo "@jjsierra0318:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - name: Sync package.json version with tag
        run: |
          TAG=${{ needs.version.outputs.new_tag }}
          VERSION=${TAG#v}
          npm version $VERSION --no-git-tag-version

      - name: Set NPM publish tag
        run: |
          if [[ "$(echo ${{ toJson(github.event.pull_request.labels) }} | grep -o '\"name\": \"renovate\"')" ]]; then
            echo "NPM_TAG=renovate" >> $GITHUB_ENV
          else
            echo "NPM_TAG=latest" >> $GITHUB_ENV
          fi

      - name: Publish to GitHub Packages
        run: npm publish --tag $NPM_TAG
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  trigger-renovate:
    if: contains(github.event.pull_request.labels.*.name, 'renovate')
    needs: 'publish-gpr'
    uses: ./.github/workflows/trigger_renovate.yml
    secrets: inherit
