name: Trigger Renovate

on:
  workflow_dispatch:
  workflow_call:

jobs:
  trigger-renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo B
        uses: actions/checkout@v3
        with:
          repository: jjsierra0318/serviceb
          token: ${{ secrets.NPM_TOKEN }}
          ref: main

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create a dummy branch and commit
        run: |
          BRANCH_NAME=renovate-trigger-$(date +%s)
          git checkout -b $BRANCH_NAME
          echo " " >> renovate.json
          git add .
          git commit -m "chore: trigger renovate scan"
          git push origin $BRANCH_NAME
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Wait for Renovate to pick up changes
        run: sleep 60 

      - name: Delete dummy branch
        run: |
          git push origin --delete $BRANCH_NAME
