name: Trigger Renovate

on:
  pull_request:
    types: [ labeled ]

jobs:
  version:
    if: ${{ github.event.label.name == 'renovate' }}
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Increment version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          initial_version: '1.0.0'  # Inicia desde v1.0.0 si no hay tags previos
          tag_prefix: 'v'
          commit_message: 'ci: Increment version to {{version}}'

  trigger_renovate:
    if: ${{ github.event.label.name == 'renovate' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Authenticate with npm
        run: |
          echo "@jjsierra0318:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - name: Install dependencies
        run: npm ci

      - name: Sync package.json version with tag
        run: |
          TAG=${{ needs.version.outputs.new_tag }}
          VERSION=${TAG#v}
          npm version $VERSION --no-git-tag-version

      - name: Publish package with tag
        run: npm publish --tag renovate